---
- hosts: logstash_server
  become: true
  tasks:
    - name: Updating apt repo on Ubuntu
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600

    - name: Upgrading all packages on Ubuntu
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true

    - name: Installing OpenJDK Java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present

    - name: Adding Elasticsearch GPG Key
      ansible.builtin.apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Adding Elasticsearch repository
      ansible.builtin.apt_repository:
        repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
        state: present
        filename: elastic-7.x.list
        update_cache: true

    - name: Transport Https for Logstash
      ansible.builtin.apt:
        name: apt-transport-https
        state: present

    # Updating and Installing the Logstash package
    - name: Installing logstash package
      ansible.builtin.apt:
        name: logstash
        update_cache: true

    # Copying The configuration file for logstash
    - name: Copying the config file for logstash
      ansible.builtin.copy:
        src: "templates/logstash.conf.j2"
        dest: "/etc/logstash/conf.d/logstash.conf"
        mode: "preseve"

    - name: Enable logstash
      ansible.builtin.systemd:
        name: logstash
        enabled: true

    - name: Start logstash
      ansible.builtin.systemd:
        name: logstash
        state: started
