---
- hosts: app_server
  become: true
  tasks:
    - name: Updating apt repo on Ubuntu
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600

    - name: Upgrading all packages on Ubuntu
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true

    - name: Installing OpenJDK Java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present

    - name: Adding Elasticsearch GPG Key
      ansible.builtin.apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Adding Elasticsearch repository
      ansible.builtin.apt_repository:
        repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
        state: present
        filename: elastic-7.x.list
        update_cache: true

    - name: Install Metricbeat onto the demo servers
      ansible.builtin.apt:
        name: metricbeat
        update_cache: true

    - name: Copying config file for Metricbeat
      ansible.builtin.copy:
        src: "templates/metricbeat.yml.j2"
        dest: "/etc/metricbeat/metricbeat.yml"
        mode: "preseve"

    - name: Enabling Metricbeat
      ansible.builtin.systemd:
        name: metricbeat
        enabled: true

    - name: Starting Metricbeat
      ansible.builtin.systemd:
        name: metricbeat
        state: started

    - name: Start metricbeats service
      ansible.builtin.service:
        name: metricbeat
        state: started

    - name: Install Filebeat onto the demo servers
      ansible.builtin.apt:
        name: filebeat
        update_cache: true

    - name: Copying config file for Filebeat
      ansible.builtin.copy:
        src: "templates/filebeat.yml.j2"
        dest: "/etc/filebeat/filebeat.yml"
        mode: "preseve"

    - name: Enabling Filebeat
      ansible.builtin.systemd:
        name: filebeat
        enabled: true

    - name: Starting Filebeat
      ansible.builtin.systemd:
        name: filebeat
        state: started

    - name: Start Filebeat service
      ansible.builtin.service:
        name: filebeat
        state: started
