---
- hosts: kibana_server
  become: true
  tasks:
    - name: Updating apt repo on Ubuntu
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600

    - name: Upgrading all packages on Ubuntu
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true

    - name: Installing OpenJDK Java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present

    - name: Adding Elasticsearch GPG Key
      ansible.builtin.apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Adding Elasticsearch repository
      ansible.builtin.apt_repository:
        repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
        state: present
        filename: elastic-7.x.list
        update_cache: true

    - name: Transport Http for Kibana
      ansible.builtin.apt:
        name: apt-transport-https
        state: present

    - name: Install Kibana with apt
      ansible.builtin.apt:
        name: kibana
        update_cache: true

    # Configurations
    - name: Updating the config file to allow outside access
      ansible.builtin.lineinfile:
        destfile: /etc/kibana/kibana.yml
        regexp: "server.host:"
        line: "server.host: 0.0.0.0"

    - name: Defining server port
      ansible.builtin.lineinfile:
        destfile: /etc/kibana/kibana.yml
        regexp: "server.port:"
        line: "server.port: 5601"

    - name: Defining Elasticsearch hosts
      ansible.builtin.lineinfile:
        destfile: /etc/kibana/kibana.yml
        regexp: "elasticsearch.hosts:"
        line: 'elasticsearch.hosts: ["{{ inventory['elasticsearch_server']['ip'] }}:9200"]'

    # Starting Kibana
    - name: Enabling Kibana
      ansible.builtin.systemd:
        name: kibana
        enabled: true

    - name: Starting Kibana
      ansible.builtin.systemd:
        name: kibana
        state: started

    - name: Starting Kibana
      ansible.builtin.service:
        name: kibana
        state: started
